### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by charignon** [kuzmisin/closurecheatsheet#12]
It seems that http://www.closurecheatsheet.com/ does not point to the content of this repo. Does the site have a new location? 

I am temporarily changing the link on the clojurescript site (https://github.com/clojure/clojurescript-site/edit/master/content/reference/google-closure-library.adoc) to point to this repo instead.

**Comment by kuzmisin** [comment]
hi @charignon 
thanks ... http://www.closurecheatsheet.com/ is no longer maintained
